### ISSUE TITLE
Need your help for my script

### ISSUE THREAD

**Issue by valm13** [FreeSapling/csgocrash#5]
Hello, can u help me ?
Since 1 month i block on my script, it doesn't change the initial bet to another bet
And where did you learn how to do these scripts ?

Script : 
`
var cashedOut = true;
var gameResult;
var gameInside;
var betAmount = 1
var cashOut = 11; // CashOut At...
var x = 1;

engine.on('game_starting', function(info) {
    //console.log('Game Starting in ' + info.time_till_start);
		placeBet();
		console.log('Placing a bet: ',betAmount);
		console.log('Var x = ',x);
});

engine.on('game_started', function(data) {
    //console.log('Game Started', data);
});

engine.on('game_crash', function(data) {
	gameResult = engine.lastGamePlay();
	gameInside = engine.lastGamePlayed();
	if (gameResult=="WON"&&gameInside==true) 
	{
	x=1;
	}
	else if (gameResult=="LOST"&&gameInside==true) 
	{
	x+=1;
	}
});
	engine.on('connect', function() {
    //console.log('Client connected, this wont happen when you run the script');
});

function placeBet() 
{
	if (x=1) {
		cashedOut = false;
		betAmount=1;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
	}
	else if(x=2){
		cashedOut = false;
		betAmount=1;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=3){
		cashedOut = false;
		betAmount=1;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=4){
		cashedOut = false;
		betAmount=1;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=5){
		cashedOut = false;
		betAmount=1;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=6){
		cashedOut = false;
		betAmount=1;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=7){
		cashedOut = false;
		betAmount=1;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=8){
		cashedOut = false;
		betAmount=1;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=9){
		cashedOut = false;
		betAmount=1;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=10){
		cashedOut = false;
		betAmount=1;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=11){
		cashedOut = false;
		betAmount=1;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=12){
		cashedOut = false;
		betAmount=2;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=13){
		cashedOut = false;
		betAmount=2;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=14){
		cashedOut = false;
		betAmount=2;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=15){
		cashedOut = false;
		betAmount=2;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=16){
		cashedOut = false;
		betAmount=2;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=17){
		cashedOut = false;
		betAmount=3;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=18){
		cashedOut = false;
		betAmount=3;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=19){
		cashedOut = false;
		betAmount=3;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=20){
		cashedOut = false;
		betAmount=3;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=21){
		cashedOut = false;
		betAmount=4;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=22){
		cashedOut = false;
		betAmount=4;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=23){
		cashedOut = false;
		betAmount=5;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=24){
		cashedOut = false;
		betAmount=5;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=25){
		cashedOut = false;
		betAmount=6;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=26){
		cashedOut = false;
		betAmount=6;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=27){
		cashedOut = false;
		betAmount=7;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=28){
		cashedOut = false;
		betAmount=7;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=29){
		cashedOut = false;
		betAmount=8;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=30){
		cashedOut = false;
		betAmount=9;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=31){
		cashedOut = false;
		betAmount=10;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=32){
		cashedOut = false;
		betAmount=11;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=33){
		cashedOut = false;
		betAmount=12;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=34){
		cashedOut = false;
		betAmount=13;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=35){
		cashedOut = false;
		betAmount=14;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=36){
		cashedOut = false;
		betAmount=16;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}
	else if(x=37){
		cashedOut = false;
		betAmount=17;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=38){
		cashedOut = false;
		betAmount=19;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=39){
		cashedOut = false;
		betAmount=21;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=40){
		cashedOut = false;
		betAmount=23;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=41){
		cashedOut = false;
		betAmount=26;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=42){
		cashedOut = false;
		betAmount=28;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=43){
		cashedOut = false;
		betAmount=31;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=44){
		cashedOut = false;
		betAmount=34;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=45){
		cashedOut = false;
		betAmount=37;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=46){
		cashedOut = false;
		betAmount=41;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=47){
		cashedOut = false;
		betAmount=45;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=48){
		cashedOut = false;
		betAmount=50;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=49){
		cashedOut = false;
		betAmount=55;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=50){
		cashedOut = false;
		betAmount=60;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=51){
		cashedOut = false;
		betAmount=66;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=52){
		cashedOut = false;
		betAmount=73;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=53){
		cashedOut = false;
		betAmount=80;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=54){
		cashedOut = false;
		betAmount=88;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=55){
		cashedOut = false;
		betAmount=97;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=56){
		cashedOut = false;
		betAmount=107;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=57){
		cashedOut = false;
		betAmount=118;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=58){
		cashedOut = false;
		betAmount=129;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=59){
		cashedOut = false;
		betAmount=142;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=60){
		cashedOut = false;
		betAmount=157;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
	else if(x=61){
		cashedOut = false;
		betAmount=172;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=62){
		cashedOut = false;
		betAmount=189;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=63){
		cashedOut = false;
		betAmount=208;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}		
	else if(x=64){
		cashedOut = false;
		betAmount=229;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=65){
		cashedOut = false;
		betAmount=252;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=66){
		cashedOut = false;
		betAmount=277;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=67){
		cashedOut = false;
		betAmount=305;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=68){
		cashedOut = false;
		betAmount=335;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=69){
		cashedOut = false;
		betAmount=369;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=70){
		cashedOut = false;
		betAmount=406;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=71){
		cashedOut = false;
		betAmount=446;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=72){
		cashedOut = false;
		betAmount=491;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=73){
		cashedOut = false;
		betAmount=540;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=74){
		cashedOut = false;
		betAmount=594;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=75){
		cashedOut = false;
		betAmount=654;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=76){
		cashedOut = false;
		betAmount=719;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=77){
		cashedOut = false;
		betAmount=791;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=78){
		cashedOut = false;
		betAmount=870;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=79){
		cashedOut = false;
		betAmount=957;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=80){
		cashedOut = false;
		betAmount=1053;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=81){
		cashedOut = false;
		betAmount=1158;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=82){
		cashedOut = false;
		betAmount=1274;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=83){
		cashedOut = false;
		betAmount=1401;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=84){
		cashedOut = false;
		betAmount=1542;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=85){
		cashedOut = false;
		betAmount=1697;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}	
	else if(x=86){
		cashedOut = false;
		betAmount=1862;
		engine.placeBet( betAmount*100, cashOut*100, true );
		console.log('Placing a bet: ',betAmount);
		}			
		
}	

	

`

**Comment by 7jacck7** [comment]
try switching betAmount100 to betAmount and cashOut100 to your cashout x
100( 200 for cashout at 2 and so on) also why is your script so
complicated? Why do you have 86 if routines if you could just do betAmount
+= 10 or something?

2016-06-17 20:04 GMT+02:00 valm13 <notifications@github.com>:

**Comment by valm13** [comment]
Its betAmount*100 but it doesn't wrote it on github idk why. and its normal if i do betamount*100, it bet betamount and not 100 times betamount. I've got 86 if because i change values of the betamount for a x streaklose. if u see its not just a +10 but more complicated ^^

**Comment by FreeSapling** [comment]
My friend, complicated or not. That is hell. Look up loops and/or switch. For your problem, I see none. It should change as you want it to?

**Comment by valm13** [comment]
Ok, i've found the problem :  my else if looks like : else if (x=1) But i forgot the second =, its if (x==1). Now my script is working

**Comment by FreeSapling** [comment]
Oh wow, how could I miss that. Lol. Good that you solved it :)
